function ui = ConsoleWindow(ui)

close(findobj('type','figure','name','Console'))

ui.console.figH = figure(4);
set(ui.console.figH,...
    'name','Console',...
    'menubar', 'none', ...
    'toolbar', 'none', ...
    'Position',[100,100,800,418]);
ui.console.outputH = uicontrol(ui.console.figH,...
    'style','listbox',...
    'position',[10,27,630,365],...
    'tag','Console Window',...
    'horizontalAlignment','left',...
    'BackgroundColor','w',...
    'max',3);
ui.console.historyH = uicontrol(ui.console.figH,...
    'style','list',...
    'position',[640,27,150,365],...
    'tag','Console History',...
    'horizontalAlignment','left',...
    'BackgroundColor','w');
uicontrol('Style', 'text',...
    'String', 'Command Window',...
    'Units','Pixels','fontsize',10,...
    'HorizontalAlignment','center',...
    'position',[11,392,628,16],...
    'FontWeight','bold');
uicontrol('Style', 'text',...
    'String', 'Command History',...
    'fontsize',10,...
    'Units','Pixels',...
    'HorizontalAlignment','center',...
    'position',[640,392,150,16],...
    'FontWeight','bold');
ui.console.cmdBoxH = uicontrol(ui.console.figH,...
    'style', 'edit',...
    'position',[10,10,780,18],...
    'BackgroundColor','w',...
    'string' , '',...
    'tag','Command Box',...
    'horizontalAlignment','left', ...
    'enable','on');
end
