function [cdf, variable, option] = InitializeStructs(testMode)

% struct of loaded cdf data
% these index names are just used to create that many variables within the
% structure.  For example, cdf is a structure of 20 elements because the
% 'index' field is set to a cell array of 20 elements.  Otherwise, these
% index names serve no other purpose.
cdfIndex = { ...
    'cdf 01'; 'cdf 02'; 'cdf 03'; 'cdf 04'; 'cdf 05'; ...
    'cdf 06'; 'cdf 07'; 'cdf 08'; 'cdf 09'; 'cdf 10'; ...
    'cdf 11'; 'cdf 12'; 'cdf 13'; 'cdf 14'; 'cdf 15'; ...
    'cdf 16'; 'cdf 17'; 'cdf 18'; 'cdf 19'; 'cdf 20' ...
    };
cdf = struct ( ...
    'index', cdfIndex, ...
    'name', {''}, ... %     'list', {''}, ...
    'finfo', {[]}, ...
    'ncid', {[]}, ...
    'varid', {[]} ,...
    'date','', ...
    'zones', [], ...
    'times', [] ...
    );
varIndex = { ...
    'var 1'; 'var 2'; ...
    'var 3'; 'var 4'; ...
    'var 5'; 'var 6' ...
    };
varFields = struct ( ...
    'name', {''}, ...
    'data', {[]}, ...
    'units', {''}, ...
    'label', {''}, ...
    'size', {[NaN,NaN]}, ...
    'max', [], ...
    'min', [] ...
    );
% struct for variable / plot data
variable = struct( ...
    'index', varIndex, ...
    'X', varFields, ...
    'Y', varFields, ...
    'T', varFields, ...
    'cdfName', {''}, ...
    'numTimes', [],...
    'numZones', [],...
    'lineWidth', [],...
    'lineStyle', {''},...
    'marker', {''},...
    'markerFill', {''},...
    'markerSize', [],...
    'color', {''}, ...
    'linePlotH', {[]}, ...
    'surfPlotH', {[]} ...
    );
% struct for gui options
SCR = get(0,'Screensize');  % Get screensize.
sliderComponent = struct( ...
    'value', 0, ...
    'max', 1, ...
    'min', 0, ...
    'step', [1/10, 1/2]);
% create slider mapping dictionary: maps from slider values to array idx
map = containers.Map;
map('TIME') = 0.01; %seconds
map('TIME3') = 0.01; %seconds
map('X') = 0.01; %normalized 
map('XB') = 0.01; %normalized
map('MCINDX') = 1/220; %normalized
map('RMAJM') = 1; %cm
map('RMJSYM') = 1; %cm
map('THETA') = 0.0628; %rad
map('ILDEN') = 1;
map('ILIM') =  1;
map('INTNC') = 1;
map('IVISB') = 1;
map('') = 0.01; % one-dimensional variables, dimensionless
% slider sub-structure
slider = struct ( ...
    'mode', 'Time', ...
    'value', 1, ...
    'max', 1, ...
    'min', 0, ...
    'step', [1/10, 1/2], ...
    'X', sliderComponent, ...
    'T', sliderComponent, ...
    'map', map);
% option structure
option = struct( ...
    'displayMode','Plot', ...
    'figSize', [SCR(3)/2-400 ,SCR(4)/2-250, 800, 500], ...
    'slider', slider, ...
    'legendLocation', 'northeast', ...
    'legendOrientation', 'vertical', ...
    'lineGrid', 'Off', ...
    'surfaceGrid', 'Off', ...
    'plotMode', 'Line Plot', ...
    'tickDirMode', 'In', ...
    'lineBox', 'On', ...
    'lineTransparency', 1, ...
    'surfaceBox', 'Off', ...
    'colorMap', 'Jet', ...
    'surfaceStyle', 'Surface Texture' ,...
    'errorLevel', 0, ...
    'testMode', testMode, ...
    'activeCdfIdx', {[]}, ...
    'cdfList', {cell(20,1)}, ...
    'leadVar', [] ...
    );

end