function htmlStr = SplashMsg(ui)
    title = '<html><body style="background-color:white;><br><div style="font-family:Arial, Helvetica, sans-serif;"><div style="font-size:24px;font-weight:bold;text-align:center;">';
    author = '</div><div style="text-align:justify;margin-top:6px;margin-right:4px;text-align:center;">';
    email = '<br>';
    newPar = '</div><div style="text-align:justify;margin-left:8px;margin-right:4px;text-indent:16px;">';
    useVersion = 'R2021b';
    htmlStr = [ ...
        title,'TRANSVIZ v2.1.0 (', useVersion, ')'...
        author,'By Christopher Wilson' ...
        email,'MetxChris@gmail.com'...
        '<br><br><br>',...
        newPar,...
        'Source code now available on github -- https://github.com/metxchris/TRANSVIZ' ...
        '</div>'
        ];
    
    set(ui.main.splashH, 'HTMLSource', htmlStr)
end

    %     newPar,...
    %     'Get started by opening a NetCDF file by using the above menu bar.  When entering in variables, the first variable is the ''primary variable'' that controls the plot axes and slider length '...
    %     'that all subsequent input variables use.  While all entered variables are plotted in ''Line Plot'' mode, only the primary variable is used in the ''Heat Map'' and ''Surface Plot'' plotting modes.'...
    %     newPar,...
    %     'Variables may be removed from the plot by deleting their entries in their corresponding entry boxes.  Deleting the master variable resets the entire plot. '...
    %     'A table of all variables within the CDF file may be found under the ''View'' user menu.  Selecting a cell on this table will automatically plot the data corresponding to the variable of the selected cell row.' ...
