function ui = BuildUI(option,variable)
%% Create user interface (ui)
ui = struct;

% main interface
ui.main.figH = figure(  ...
    'name','TRANSVIZ',...
    'menubar',   'none',...
    'Units'     , 'Pixels'    , ...
    'toolbar','none',...
    'Position',option.figSize,...
    'renderer','opengl',...
    'DefaultTextInterpreter','TeX');
ui.main.axesH = axes(                 ...
    'Units', 'Pixels'     ,...
    'visible','off');
ui.main.activeCdfH = uicontrol(...
    'Style', 'popupmenu',...
    'String', option.cdfList,...
    'Units','Pixels',...
    'enable','off',...
    'HorizontalAlignment','left');
% limits combobox entries (buggy though)
% jCombobox = findjobj(ui.main.activeCdfH);
% jCombobox.setMaximumRowCount(5);
ui.main.splashH = uicontrol(...
    'style','edit',...
    'max',5);
ui.main.sliderH = uicontrol( ...
    'Style'     , 'Slider'    , ...
    'Units'     , 'Pixels'    , ...
    'Min'       , 1           , ...
    'Max'       , 10           , ...
    'Value'     , option.sliderValue  , ...
    'enable','off'...
    );
ui.main.globalValuesH = uicontrol(...
    'Style', 'text',...
    'String', 'Global Values:',...
    'Units','Pixels',...
    'HorizontalAlignment','left',...
    'visible','off',...
    'FontWeight','bold');
ui.main.plotTimeH = text(...
    1,1,'',...
    'units','pixels',...
    'horiz','right',...
    'vert','baseline',...
    'fontsize',8 );
ui.main.textHeaderH(1) = uicontrol(...
    'Style', 'text',...
    'String', 'Active CDF:',...
    'Units','Pixels',...
    'HorizontalAlignment','left',...
    'FontWeight','bold');
ui.main.textHeaderH(2) = uicontrol(...
    'Style', 'text',...
    'String', 'Variable Entry:',...
    'Units','Pixels',...
    'HorizontalAlignment','left',...
    'FontWeight','bold');
ui.main.textHeaderH(3) = uicontrol(...
    'Style', 'text',...
    'String', 'Slider Mode:',...
    'Units','Pixels',...
    'HorizontalAlignment','left',...
    'visible','on',...
    'FontWeight','bold');
ui.main.entryLabelH(1) = uicontrol(...
    'Style', 'text',...
    'String', '1)',...
    'Units','Pixels',...
    'HorizontalAlignment','left');
ui.main.entryLabelH(2) = uicontrol(...
    'Style', 'text',...
    'String', '2)',...
    'Units','Pixels',...
    'HorizontalAlignment','left');
ui.main.entryLabelH(3) = uicontrol(...
    'Style', 'text',...
    'String', '3)',...
    'Units','Pixels',...
    'HorizontalAlignment','left');
ui.main.entryLabelH(4) = uicontrol(...
    'Style', 'text',...
    'String', '4)',...
    'Units','Pixels',...
    'HorizontalAlignment','left');
ui.main.entryLabelH(5) = uicontrol(...
    'Style', 'text',...
    'String', '5)',...
    'Units','Pixels',...
    'HorizontalAlignment','left');
ui.main.entryLabelH(6) = uicontrol(...
    'Style', 'text',...
    'String', '6)',...
    'Units','Pixels',...
    'HorizontalAlignment','left');
ui.main.entryHelpH(1) = uicontrol(...
    'Style', 'text',...
    'String', '+',...
    'Units','Pixels',...
    'visible','off',...
    'foregroundcolor',variable(1).color,...
    'HorizontalAlignment','left');
ui.main.entryHelpH(2) = uicontrol(...
    'Style', 'text',...
    'String', '+',...
    'Units','Pixels',...
    'visible','off',...
    'foregroundcolor',variable(2).color,...
    'HorizontalAlignment','left');
ui.main.entryHelpH(3) = uicontrol(...
    'Style', 'text',...
    'String', '+',...
    'Units','Pixels',...
    'visible','off',...
    'foregroundcolor',variable(3).color,...
    'HorizontalAlignment','left');
ui.main.entryHelpH(4) = uicontrol(...
    'Style', 'text',...
    'String', '+',...
    'Units','Pixels',...
    'visible','off',...
    'foregroundcolor',variable(4).color,...
    'HorizontalAlignment','left');
ui.main.entryHelpH(5) = uicontrol(...
    'Style', 'text',...
    'String', '+',...
    'Units','Pixels',...
    'visible','off',...
    'foregroundcolor',variable(5).color,...
    'HorizontalAlignment','left');
ui.main.entryHelpH(6) = uicontrol(...
    'Style', 'text',...
    'String', '+',...
    'Units','Pixels',...
    'visible','off',...
    'foregroundcolor',variable(6).color,...
    'HorizontalAlignment','left');
ui.main.entryBoxH(1) = uicontrol(...
    'style', 'edit',...
    'string' , '',...
    'tag','1',...
    'enable','off');
ui.main.entryBoxH(2) = uicontrol(...
    'style', 'edit',...
    'string' , '',...
    'tag','2', ...
    'enable','off');
ui.main.entryBoxH(3) = uicontrol(...
    'style', 'edit',...
    'string' , '',...
    'tag','3', ...
    'enable','off');
ui.main.entryBoxH(4) = uicontrol(...
    'style', 'edit',...
    'string' , '',...
    'tag','4', ...
    'enable','off');
ui.main.entryBoxH(5) = uicontrol(...
    'style', 'edit',...
    'string' , '',...
    'tag','5', ...
    'enable','off');
ui.main.entryBoxH(6) = uicontrol(...
    'style', 'edit',...
    'string' , '',...
    'tag','6', ...
    'enable','off');
ui.main.sliderModeH = uibuttongroup(...
    'visible','on',...
    'units','pixels',...
    'bordertype','none',...
    'SelectedObject',[]);
ui.main.sliderModeB(1) = uicontrol('style','toggle',...
    'units','pixels',...
    'string','Time',...
    'parent',ui.main.sliderModeH,...
    'backgroundcolor',[241/255 241/255 241/255],...
    'val',1,...
    'enable','off');
ui.main.sliderModeB(2) = uicontrol('style','toggle',...
    'units','pixels',...
    'string','Position',...
    'value',0,...
    'parent',ui.main.sliderModeH,...
    'enable','off');
ui.main.systemMsgH = uicontrol(...
    'Style', 'text',...
    'string','',...
    'Units','Pixels',...
    'HorizontalAlignment','center',...
    'fontsize',9);

% create top menu
ui.menu.fileMH = uimenu(ui.main.figH,...
    'Label','&File');
ui.menu.openFMH = uimenu(ui.menu.fileMH,...
    'Label','&Open CDF...');
ui.menu.exportFigureMH = uimenu(ui.menu.fileMH,...
    'Label','Export &Figure',...
    'separator','on');
ui.menu.exportDataMH = uimenu(ui.menu.fileMH,...
    'Label','Export &Data',...
    'enable','on');
ui.menu.editMH = uimenu(ui.main.figH,...
    'Label','&Edit');
ui.menu.plotModeMH = uimenu(ui.menu.editMH,...
    'Label','&Plot Mode');
ui.menu.plotModeH(1) = uimenu(ui.menu.plotModeMH,...
    'Label','&Line Plot');
ui.menu.plotModeH(2) = uimenu(ui.menu.plotModeMH,...
    'Label','&Surface Plot', ...
    'enable', 'off');
ui.menu.rendererMH = uimenu(ui.menu.editMH,...
    'Label','&Renderer');
ui.menu.rendererH(1) = uimenu(ui.menu.rendererMH,...
    'Label','&OpenGL');
ui.menu.rendererH(2) = uimenu(ui.menu.rendererMH,...
    'Label','&Painters');
ui.menu.surfaceGridHM = uimenu(ui.menu.editMH, ...
    'Label','&Surface Style', ...
    'visible','off', ...
    'separator','on');
ui.menu.surfaceGridH(1) = uimenu(ui.menu.surfaceGridHM, ...
    'Label','&Surface Texture', ...
    'tag','surfaceGridHM');
ui.menu.surfaceGridH(2) = uimenu(ui.menu.surfaceGridHM, ...
    'Label','&Surface Grid',...
    'tag','surfaceGridHM');
ui.menu.surfaceGridH(3) = uimenu(ui.menu.surfaceGridHM, ...
    'Label','&Mesh Grid',...
    'tag','surfaceGridHM');
ui.menu.colorMapHM = uimenu(ui.menu.editMH, ...
    'Label','&Color Map', ...
    'visible','off');
ui.menu.colorMapH(1) = uimenu(ui.menu.colorMapHM, ...
    'Label','&Jet', ...
    'tag','colorMapHM');
ui.menu.colorMapH(2) = uimenu(ui.menu.colorMapHM, ...
    'Label','&Hsv',...
    'tag','colorMapHM');
ui.menu.colorMapH(3) = uimenu(ui.menu.colorMapHM,...
    'Label','&Bone',...
    'tag','colorMapHM');
ui.menu.axesBoxModeHM = uimenu(ui.menu.editMH, ...
    'Label','Axes &Box', ...
    'separator','on');
ui.menu.axesBoxModeH(1) = uimenu(ui.menu.axesBoxModeHM,...
    'Label','O&n',...
    'tag','axesBoxModeHM');
ui.menu.axesBoxModeH(2) = uimenu(ui.menu.axesBoxModeHM,...
    'Label','O&ff',...
    'tag','axesBoxModeHM');
ui.menu.gridModeHM = uimenu(ui.menu.editMH,...
    'Label','&Grid Lines');
ui.menu.gridModeH(1) = uimenu(ui.menu.gridModeHM,...
    'Label','O&n',...
    'tag','gridModeHM');
ui.menu.gridModeH(2) = uimenu(ui.menu.gridModeHM,...
    'Label','O&ff',...
    'tag','gridModeHM');
ui.menu.legendLocationHM = uimenu(ui.menu.editMH,...
    'Label','&Legend Location');
ui.menu.legendLocationH(1) = uimenu(ui.menu.legendLocationHM,...
    'Label','&NorthEast',...
    'tag','legendLocationHM');
ui.menu.legendLocationH(2) = uimenu(ui.menu.legendLocationHM,...
    'Label','North&West',...
    'tag','legendLocationHM');
ui.menu.legendLocationH(3) = uimenu(ui.menu.legendLocationHM,...
    'Label','South&East',...
    'tag','legendLocationHM');
ui.menu.legendLocationH(4) = uimenu(ui.menu.legendLocationHM,...
    'Label','&SouthWest',...
    'tag','legendLocationHM');
ui.menu.toolsMH = uimenu(ui.main.figH,...
    'Label','&Tools');
ui.menu.ResetViewH=uimenu(ui.menu.toolsMH,...
    'Label','&Reset View');
ui.menu.ZoomInH=uimenu(ui.menu.toolsMH,...
    'Label','&Zoom In',...
    'separator', 'on');
ui.menu.PanH=uimenu(ui.menu.toolsMH,...
    'Label','&Pan');
ui.menu.windowMH = uimenu(ui.main.figH,...
    'Label','&Window');
ui.menu.varListH=uimenu(ui.menu.windowMH,...
    'Label','&Variable List');
ui.menu.consoleMH = uimenu(ui.menu.windowMH,...
    'Label','&Console');
% Set Background Color of relevant uicontrols
SetBackgroundColor(ui,'gray');
% printing options
set(ui.main.figH, 'InvertHardCopy', 'off');
set(0, 'DefaultFigureInvertHardcopy', 'on')
set(ui.main.figH, 'PaperPositionMode', 'auto');
% greatly speedup slider updates when legends are displayed
setappdata(gca,'LegendColorbarManualSpace',1);
setappdata(gca,'LegendColorbarReclaimSpace',1);
% modify tooltip properties
tm = javax.swing.ToolTipManager.sharedInstance; %static method to get ToolTipManager object
javaMethodEDT('setInitialDelay',tm,0); %set tooltips to appear immediately
javaMethodEDT('setDismissDelay',tm,600000); %tootips disappear after 10min.

end