function [cdf,variable,option] = InitializeStructs(testMode)

% struct of loaded cdf data
cdfIndex = { ...
    'cdf 01'; 'cdf 02'; 'cdf 03'; 'cdf 04'; 'cdf 05'; ...
    'cdf 06'; 'cdf 07'; 'cdf 08'; 'cdf 09'; 'cdf 10'; ...
    'cdf 11'; 'cdf 12'; 'cdf 13'; 'cdf 14'; 'cdf 15'; ...
    'cdf 16'; 'cdf 17'; 'cdf 18'; 'cdf 19'; 'cdf 20' ...
    };
cdf = struct ( ...
    'index', cdfIndex, ...
    'name', {''}, ... %     'list', {''}, ...
    'finfo', {[]}, ...
    'ncid', {[]}, ...
    'varid', {[]} ,...
    'date','', ...
    'zones', [], ...
    'times', [] ...
    );
varIndex = { ...
    'var 1'; 'var 2'; ...
    'var 3'; 'var 4'; ...
    'var 5'; 'var 6' ...
    };
varFields = struct ( ...
    'name', {''}, ...
    'data', {[]}, ...
    'units', {''}, ...
    'label', {''}, ...
    'size', {[NaN,NaN]}, ...
    'max', [], ...
    'min', [] ...
    );
lineColors = { ...
    [0.094 0.353 0.663];        ...     % blue
    [0.933 0.180 0.184];        ...     % red
    [0 0.549 0.282];            ...     % green
    [0.4 0.173 0.569];          ...     % purple
    [0.957 0.490 0.137];        ...     % orange
    1-[0.933 0.180 0.184]       ...     % cyan
    };
% struct for variable / plot data
variable = struct( ...
    'index', varIndex, ...
    'X', varFields, ...
    'Y', varFields, ...
    'T', varFields, ...
    'cdfName', {''}, ...
    'numTimes',[],...
    'numZones',[],...
    'lineWidth',{1.75;1.75;1.5;1.5;1.25;1.25},...
    'lineStyle',{'-';'-.';'-';'-.';'-';'-.'},...
    'marker',{'none'},...
    'markerFill',{'none'},...
    'markerSize',{6},...
    'color',lineColors, ...
    'linePlotH', {[]} ...
    );
% struct for gui options
SCR = get(0,'Screensize');  % Get screensize.
sliderComponent = struct( ...
    'value', 0, ...
    'max', 1, ...
    'min', 0, ...
    'step', [1/10, 1/2]);
slider = struct ( ...
    'mode', 'Time', ...
    'value', 0, ...
    'max', 1, ...
    'min', 0, ...
    'step', [1/10, 1/2], ...
    'X', sliderComponent, ...
    'T', sliderComponent);
option = struct( ...
    'displayMode','Plot', ...
    'figSize', [SCR(3)/2-400 ,SCR(4)/2-250,800,500], ...
    'slider', slider, ...
    'sliderValue', 1, ...
    'sliderValueX', 1, ...
    'sliderValueT', 1, ...
    'sliderMax', 10, ...
    'sliderMin', 1, ...
    'sliderStep', [1/10,1/2], ...
    'sliderMode', 'Time', ...
    'systemMsg', 0, ...
    'axisMode', 'Global', ...
    'legendLocation', 'northeast', ...
    'legendOrientation', 'vertical', ...
    'gridMode', 'Off', ...
    'colorMode', 1, ...
    'plotMode', 'Line Plot', ...
    'tickDirMode', 'In', ...
    'axesBoxMode', 'On', ...
    'colorMap', 'Jet', ...
    'surfaceGrid', 'Surface Texture' ,...
    'errorLevel', 0, ...
    'testMode', testMode, ...
    'activeCdfIdx', {[]}, ...
    'cdfList', {cell(20,1)}, ...
    'entryBoxNumber', 1, ...
    'leadVar', [] ...
    );

end