function ui = VarListWindow(cdf, option, ui)
% Close old varlist window
if ~isempty(findobj('type','figure','name','Variable List'))
    fP = get(findobj('type','figure','name','Variable List'), 'position');
    position = [fP(1) fP(2) 669 420];
    close(findobj('type','figure','name','Variable List'));
else 
    position= [100,100,669,420];
end

finfo = cdf(option.activeCdfIdx).finfo;
varList = {finfo.Variables.Name};

% tic

ncDataType = 'single';
j=1:numel(varList);
tempData = {finfo.Variables(1,j).Datatype};
tempData = tempData(strncmp(tempData,ncDataType,6));



cdfVarCount = numel(tempData);
varTable = cell(cdfVarCount,6);
varRange=1:cdfVarCount;
varNum = strtrim(cellstr(num2str(varRange')));
varNames = {finfo.Variables(1,1:cdfVarCount).Name}';
fAttributes = [finfo.Variables(1,1:cdfVarCount).Attributes];
varDesc = deblank({fAttributes(2:2:2*cdfVarCount).Value}');
varUnits = deblank({fAttributes(1:2:2*cdfVarCount).Value}');

% cdfVarCount2 = numel(varList);
% varTable = cell(cdfVarCount2-cdfVarCount,6);
% varRange=cdfVarCount+1:cdfVarCount2;
% varNum = strtrim(cellstr(num2str(varRange')));
% varNames = {finfo.Variables(1,cdfVarCount+1:cdfVarCount2).Name}';
% fAttributes2 = [finfo.Variables(1,cdfVarCount+1:cdfVarCount2).Attributes];
% varDesc = deblank({fAttributes2(2:3:end).Value}');
% varUnits = deblank({fAttributes2(1:3:end).Value}');
% varIDs = {fAttributes2(3:3:end).Value}';

varTable(:,1) = varNum;
varTable(:,2) = varNames;
varTable(:,3) = varDesc;
varTable(:,6) = varUnits;
% Cols 4,5 set in loop below

% % fSize={finfo.Variables(1,1:cdfVarCount).Size}';
% % varSize= cell(cdfVarCount,1);


% zones = fSize{1};
for j = varRange
    %     use with zones variable
    %     if numel(fSize{j})==1
    %         varSize{j}=1;
    %     else
    %         varSize{j}=fSize{j}(1);
    %     end
    
    
    jSize = finfo.Variables(1,j).Size;
    if numel(jSize) == 1
        varTable(j,4) = {num2str(jSize)};
    elseif  numel(jSize) == 2
        varTable(j,4) = {[num2str(jSize(1,1)),' x ',num2str(jSize(1,2))]};
    end
    
    jDim = numel(finfo.Variables(1,j).Dimensions);
    if jDim == 1
        varTable(j,5) = {finfo.Variables(1,j).Dimensions(1,1).Name};
    elseif  jDim == 2
        varTable(j,5) = {[finfo.Variables(1,j).Dimensions(1,1).Name, ...
            ', ',finfo.Variables(1,j).Dimensions(1,2).Name]};
    end
    
end


% toc

buttonColor = [240/255,240/255,240/255]; %gray
ColumnNames = {'VarID','Name','Description','Size','Dimensions','Units'};
htmlString = '<html><div style="color:rgb(24,90,169);font-weight:bold">';

ui.varlist.figH = figure(2);
set(ui.varlist.figH,...
    'name','Variable List',...
    'Position',position);
ui.varlist.tableH = uitable(ui.varlist.figH,...
    'Units','Pixels',...
    'Position', [10,10,649,400],...
    'ColumnWidth', {70 80 220 70 90 100},...
    'ColumnName', ColumnNames,...
    'RowName', [],...
    'tag','1',...
    'data',varTable);
ui.varlist.varidBH = uicontrol(ui.varlist.figH,...
    'Style','pushbutton',...
    'Units','Pixels',...
    'string',[htmlString,'VarID</div>'],...
    'Position',[11,390,69,19],...
    'enable','on',...
    'tag','VarId',...
    'HorizontalAlignment','center');
ui.varlist.nameBH = uicontrol(ui.varlist.figH,...
    'Style', 'pushbutton',...
    'Units','Pixels',...
    'string',[htmlString,'Name</div>'],...
    'Position',[80,390,79,19],...
    'enable','on',...
    'tag','Name',...
    'backgroundColor',buttonColor,...
    'HorizontalAlignment','center');
ui.varlist.descriptionBH = uicontrol(ui.varlist.figH,...
    'Style', 'pushbutton',...
    'Units','Pixels',...
    'string',[htmlString,'Description</div>'],...
    'Position',[160,390,219,19],...
    'enable','on',...
    'tag','Description',...
    'backgroundColor',buttonColor,...
    'HorizontalAlignment','center');
ui.varlist.sizeBH = uicontrol(ui.varlist.figH,...
    'Style', 'pushbutton',...
    'Units','Pixels',...
    'string',[htmlString,'Size</div>'],...
    'Position',[380,390,69,19],...
    'enable','on',...
    'tag','Size',...
    'backgroundColor',buttonColor,...
    'HorizontalAlignment','center');
ui.varlist.dimensionsBH = uicontrol(ui.varlist.figH,...
    'Style', 'pushbutton',...
    'Units','Pixels',...
    'string',[htmlString,'Dimensions</div>'],...
    'Position',[450,390,89,19],...
    'enable','on',...
    'tag','Dimensions',...
    'backgroundColor',buttonColor,...
    'HorizontalAlignment','center');
ui.varlist.unitsBH = uicontrol(ui.varlist.figH,...
    'Style', 'pushbutton',...
    'Units','Pixels',...
    'string',[htmlString,'Units</div>'],...
    'Position',[540,390,100,19],...
    'enable','on',...
    'tag','Units',...
    'backgroundColor',buttonColor,...
    'HorizontalAlignment','center');


try
    % apply java techniques to edit button properties
    buttonEdit(ui.varlist.varidBH);
    buttonEdit(ui.varlist.nameBH);
    buttonEdit(ui.varlist.descriptionBH);
    buttonEdit(ui.varlist.sizeBH);
    buttonEdit(ui.varlist.dimensionsBH);
    buttonEdit(ui.varlist.unitsBH);
catch err %#ok<NASGU>
    %do nothing
end

    function buttonEdit(handle)
        jButton = java(findjobj(handle));
        jButton.setCursor(java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton.setFlyOverAppearance(true);
    end

end